In [3]:
import numpy as np
np.__version__

'1.19.1'

## 1. 基本类型

### 1.1 ndarray

In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5 6]


### 1.2 matrix

In [15]:
b = np.mat(a)
print(type(b), b)

<class 'numpy.matrix'> [[1 2 3 4 5 6]]


## 2. 初期化

### 2.1 array

In [16]:
n1array = np.array([1, 2, 3, 4, 5, 6]) # 一维
print(n1array.shape, n1array)

(6,) [1 2 3 4 5 6]


In [11]:
n2array = np.array([[1, 2, 3], [4, 5, 6]]) # 二维
print(n2array.shape, n2array)

(2, 3) [[1 2 3]
 [4 5 6]]


### 2.2 zeros

In [17]:
n1zeros = np.zeros(6) # 一维
print(n1zeros.shape, n1zeros)

(6,) [0. 0. 0. 0. 0. 0.]


In [18]:
n2zeros = np.zeros((2,3)) # 二维
print(n2zeros.shape, n2zeros)

(2, 3) [[0. 0. 0.]
 [0. 0. 0.]]


### 2.3 ones

In [19]:
n1ones = np.ones(6) # 一维
print(n1ones.shape, n1ones)

(6,) [1. 1. 1. 1. 1. 1.]


In [20]:
n2ones = np.ones((2,3)) # 二维
print(n2ones.shape, n2ones)

(2, 3) [[1. 1. 1.]
 [1. 1. 1.]]


### 2.4 empty

In [21]:
n1empty = np.empty(6) # 一维
print(n1empty.shape, n1empty)

(6,) [0. 0. 0. 0. 0. 0.]


In [22]:
n2empty = np.empty((2,3)) # 二维
print(n2empty.shape, n2empty)

(2, 3) [[0. 0. 0.]
 [0. 0. 0.]]


### 2.5 arange

In [23]:
n1arange = np.arange(6) # 一维
print(n1arange.shape, n1arange)

(6,) [0 1 2 3 4 5]


In [25]:
n2arange = np.arange(6).reshape(2,3) # 二维
print(n2arange.shape, n2arange)

(2, 3) [[0 1 2]
 [3 4 5]]


### 2.6 linspace

In [28]:
n1linspace = np.linspace(0, 10, num=6) # 一维
print(n1linspace.shape, n1linspace)

(6,) [ 0.  2.  4.  6.  8. 10.]


In [29]:
n2linspace = np.linspace(0, 10, num=6).reshape(2,3) # 二维
print(n2linspace.shape, n2linspace)

(2, 3) [[ 0.  2.  4.]
 [ 6.  8. 10.]]


## 3. 算法

### 3.1 和

In [10]:
n1sum = np.array([1, 2, 3, 4]).reshape((4, 1)) # 一维
print(n1sum.shape, n1sum)
np.sum(n1sum[0:2])

(4, 1) [[1]
 [2]
 [3]
 [4]]


3